---
- name: Install mysql community repo
  yum:
    name: "http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm"
    state: present

- name: Install mysql database
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - "mysql-server"
    - "mysql-devel"

- name: Start MySQL Service
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Install mysql-python package
  yum:
    name: MySQL-python
    state: present

- name: Create Application Database
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Create Database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present
# tasks file for mysql_db
